# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

ANSIBLE_ANSIBLE_LINT_PRE_COMMANDS:
  - { "command": "ansible-galaxy install -r ansible/requirements.yml" }
ANSIBLE_ANSIBLE_LINT_ARGUMENTS: ansible
ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: ansible/.ansible-lint

BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - SPELL_CSPELL

# Remove: To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
EMAIL_REPORTER: false

FAIL_IF_MISSING_LINTER_IN_FLAVOR: true

FILTER_REGEX_EXCLUDE: CHANGELOG.md

FORMATTERS_DISABLE_ERRORS: false

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

# Remove initial MegaLinter graphic
PRINT_ALPACA: false

# Disable creating report directory
REPORT_OUTPUT_FOLDER: none

# Overwritten by .github/workflows/megalinter.yml
VALIDATE_ALL_CODEBASE: false
