# https://lychee.cli.rs/#/usage/config

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs
cache = true

# Discard all cached requests older than this duration
max_cache_age = "1d"

#############################  Runtime  #############################

# Maximum number of concurrent link checks
max_concurrency = 128

#############################  Exclusions  ##########################

exclude = [
  'http://raspi.xvx.cz.*',
  'https://pkg.cloudflare.com/cloudflared',
]

# Exclude these filesystem paths from getting checked
exclude_path = []
