[tools]
ansible = "14.2.0"
fnox = "1.30.0"

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
_.fnox-env = { tools = true }

[tasks.run]
description = "Run Ansible playbook"
dir = "ansible"
shell = "bash -c"
run = """
set -euo pipefail
ansible-galaxy install -r requirements.yml
ansible-playbook --diff -i inventory/hosts main.yml 2>&1 | tee /tmp/ansible-raspberry-pi-os.log
"""
