[tools]
# ansible = "latest"
fnox = "1.19.0"

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
_.fnox-env = { tools = true }

[tasks.run]
description = "Run Ansible playbook"
dir = "ansible"
shell = "bash -c"
run = """
set -euxo pipefail
ansible-galaxy install -r requirements.yml
if [ ! -f /tmp/ansible-raspberry-pi-os.log ]; then
  ansible-playbook --diff --user root -i inventory/hosts main.yml 2>&1 | tee /tmp/ansible-raspberry-pi-os.log
else
  ansible-playbook --diff --user root -i inventory/hosts main.yml
fi
"""
