# keep-sorted start
alloy_grafana_cloud_loki_url: "https://logs-prod-012.grafana.net/loki/api/v1/push"
alloy_grafana_cloud_loki_username: 911770
alloy_grafana_cloud_password: "{{ lookup('env', 'ALLOY_GRAFANA_CLOUD_PASSWORD') }}"
alloy_grafana_cloud_prometheus_url: "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
alloy_grafana_cloud_prometheus_username: 1623667
# renovate: datasource=github-tags depName=grafana/alloy
alloy_grafana_version: 1.16.0
backup_directory: /mnt/backups/raspi
backup_server: 192.168.1.1
backup_user: root
bluetooth_device_address_headset: 08:C8:C2:85:EF:57 # Device 08:C8:C2:85:EF:57 PetrR Jabra Evolve2 55
bluetooth_device_address_rpi: DC:A6:32:0E:BD:15
# https://thesmarthomejourney.com/2022/08/01/fixing-cadvisor-cpu/
# https://github.com/docker/for-linux/issues/1112 - Grafana -> Cadvisor exprter -> Memory
boot_cmdline_parameters: cgroup_enable=cpuset cgroup_enable=memory psi=1
boot_config_parameters: |
  hdmi_ignore_cec_init=1
cloudflared_tunnel_token: "{{ lookup('env', 'CLOUDFLARED_TUNNEL_TOKEN') }}"
docker_config:
  metrics-addr: 127.0.0.1:9323
docker_container_timeout: 500
esphome_api_encryption_key: "{{ lookup('env', 'ESPHOME_API_ENCRYPTION_KEY') }}"
esphome_ota_password: "{{ lookup('env', 'ESPHOME_OTA_PASSWORD') }}"
esphome_web_server_password: "{{ lookup('env', 'ESPHOME_WEB_SERVER_PASSWORD') }}"
esphome_web_server_username: admin
firewall_additional_rules:
  - "iptables -A INPUT -m pkttype --pkt-type multicast -j ACCEPT"
  - "iptables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"
firewall_allowed_tcp_ports: "{{ fw_allowed_tcp_ports }}"
firewall_allowed_udp_ports: "{{ fw_allowed_udp_ports }}"
firewall_forwarded_tcp_ports: "{{ fw_forwarded_tcp_ports }}"
firewall_log_dropped_packets: false
fw_allowed_tcp_ports:
  - 22 # SSH
  - 22222 # SSH
  - 1883 # MQTT
fw_allowed_udp_ports:
  - 1883 # MQTT
  - 5353 # mDNS - avahi-daemon
fw_forwarded_tcp_ports:
  - src: 22222
    dest: 22
grafana_dashboards:
  # 1617-systemd-service-dashboard
  - dashboard_id: 1617
    revision_id: 1
    datasource: prometheus
  # 1860-node-exporter-full
  - dashboard_id: 1860
    revision_id: 37
    datasource: prometheus
  # 16124-blackbox-exporter
  - dashboard_id: 16124
    revision_id: 2
    datasource: prometheus
  # 18153-openwrt
  - dashboard_id: 18153
    revision_id: 3
    datasource: prometheus
  # 18538-blackbox-exporter
  - dashboard_id: 18538
    revision_id: 1
    datasource: prometheus
  # 18999-grafana-metrics
  - dashboard_id: 18999
    revision_id: 1
    datasource: prometheus
  # 19268-prometheus
  - dashboard_id: 19268
    revision_id: 1
    datasource: prometheus
  # 19908-docker-container-monitoring-with-prometheus-and-cadvisor
  - dashboard_id: 19908
    revision_id: 1
    datasource: prometheus
  # 21040-docker-daemons
  - dashboard_id: 21040
    revision_id: 1
    datasource: prometheus
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    basicAuth: false
    isDefault: true
grafana_ini:
  auth:
    disable_login_form: true
    anonymous:
      enabled: true
      org_role: Admin
  security:
    admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
    allow_embedding: true
    cookie_samesite: none
  server:
    http_addr: 127.0.0.1
    http_port: 3001
    root_url: https://grafana-rpi.xvx.cz
  smtp:
    enabled: true
    host: smtp.gmail.com:587
    user: "{{ smtp_gmail_auth_user }}"
    password: "{{ smtp_gmail_auth_password }}"
# renovate: datasource=github-tags depName=grafana/grafana
grafana_version: 13.0.1
hass_config_directory: /var/lib/hass_config
hass_url: https://hass-rpi.xvx.cz
hass_user_password: "{{ lookup('env', 'HASS_USER_PASSWORD') }}"
kernel_modules:
  - nf_conntrack
kodi_guisettings_services_webserverpassword: "{{ lookup('env', 'KODI_GUISETTINGS_SERVICES_WEBSERVERPASSWORD') }}"
mqtt_clients:
  zigbee2mqtt:
    user: zigbee2mqtt
    password: "{{ lookup('env', 'MQTT_ZIGBEE2MQTT_PASSWORD') }}"
  uzg-01:
    user: uzg-01
    password: "{{ lookup('env', 'MQTT_UZG01_PASSWORD') }}"
notification_email: petr.ruzicka@gmail.com
ntp_server: ntp.nic.cz
openwrt_homepage_password: "{{ lookup('env', 'OPENWRT_HOMEPAGE_PASSWORD') }}"
openwrt_ip: 192.168.1.1
openwrt_luci_password: "{{ lookup('env', 'OPENWRT_LUCI_PASSWORD') }}"
openwrt_luci_user: root
prometheus_hass_bearer_token: "{{ lookup('env', 'PROMETHEUS_HASS_BEARER_TOKEN') }}"
# renovate: datasource=github-tags depName=prometheus/prometheus
prometheus_version: 3.11.2
prometheus_web_external_url: https://prometheus-rpi.xvx.cz
prometheus_web_listen_address: 127.0.0.1:9090
rpi_disable_boot_services:
  - cloud-config.service
  - cloud-final.service
  - cloud-init-local.service
  - cloud-init-main.service
  - cloud-init-network.service
  - console-setup
  - dnsmasq
  - keyboard-setup
  - ModemManager
  - regenerate_ssh_host_keys
  - sshd-keygen
  - sshswitch
rpi_packages:
  - bsd-mailx
  - dma
  - dnsmasq
  - fzf
  - htop
  - jq
  - knot-dnsutils
  - kodi
  - mc
  - pipewire-audio
  - python3-debian
  - smartmontools
  - sqlite3
  - telnet
  - unattended-upgrades
  - vim
  - wireplumber
rpi_password: "{{ lookup('env', 'RPI_PASSWORD') }}"
smtp_gmail_auth_password: "{{ lookup('env', 'SMTP_GMAIL_AUTH_PASSWORD') }}"
smtp_gmail_auth_user: my.user.mbox@gmail.com
timezone: Europe/Prague
transmission_ip: 192.168.1.1
transmission_rpc_password: "{{ lookup('env', 'TRANSMISSION_RPC_PASSWORD') }}"
uptimerobot_api_key: "{{ lookup('env', 'UPTIMEROBOT_API_KEY') }}"
wifi_24ghz_ssid: "{{ lookup('env', 'WIFI_24GHZ_SSID') }}"
wifi_password: "{{ lookup('env', 'WIFI_PASSWORD') }}"
zigbee2mqtt_ext_pan_id: "{{ lookup('env', 'ZIGBEE2MQTT_EXT_PAN_ID') }}"
zigbee2mqtt_network_key: "{{ lookup('env', 'ZIGBEE2MQTT_NETWORK_KEY') }}"
zigbee2mqtt_pan_id: "{{ lookup('env', 'ZIGBEE2MQTT_PAN_ID') }}"
zigbee_coordinator_ip: 192.168.1.3
# keep-sorted end
