---
collections:
  # keep-sorted start
  - name: ansible.posix
    version: 2.2.2
  - name: community.docker
    version: 5.2.1
  - name: community.general
    version: 13.1.0
  - name: grafana.grafana
    version: 6.1.0
  - name: prometheus.prometheus
    version: 0.30.0
  # keep-sorted end
