modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: ip4
  tcp_connect:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
  ssh_banner:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
      query_response:
        - expect: "^SSH-2.0-"
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: ip4
