---
- name: Set timezone to Europe/Prague
  timezone:
    name: Europe/Prague

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to '/etc/hosts'
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ inventory_hostname }}.*'
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
  when: ansible_default_ipv4.address is defined

- name: Configure NTP
  ini_file:
    path: /etc/systemd/timesyncd.conf
    no_extra_spaces: yes
    section: Time
    option: NTP
    value: "{{ ntp_server }}"

- name: Copy sshd keys to /etc/ssh/
  copy:
    src: files/etc/ssh/{{ inventory_hostname }}/
    dest: /etc/ssh/
    mode: 0600
  notify: restart sshd

- name: Chnage pi and root user password
  user:
    name: "{{ item }}"
    password: "{{ rpi_password | string | password_hash('sha512') }}"
  changed_when: false
  loop:
    - pi
    - root

- name: Set authorized key for pi and root
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  loop:
    - pi
    - root

- name: Create /etc/systemd/journald.conf.d directory
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: Forward journald to /dev/tty12
  ini_file:
    path: /etc/systemd/journald.conf.d/fw-tty12.conf
    no_extra_spaces: yes
    section: Journal
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - option: ForwardToConsole
      value: "yes"
    - option: TTYPath
      value: /dev/tty12
    - option: MaxLevelConsole
      value: info
  notify: reload systemd

- name: Configure journald
  ini_file:
    path: /etc/systemd/journald.conf.d/journal-size.conf
    section: Journal
    option: SystemMaxUse
    value: 1M
  notify: reload systemd

- name: Configure .bashrc for root
  blockinfile:
    dest: /root/.bashrc
    block: |
      PS1='\[\033[01;31m\]\h\[\033[01;34m\] \w #\[\033[00m\] '
      alias ll='ls -l --color=auto'
      alias mynmon='tmux new-session "NMON=tl nmon -s 3" \; split-window "NMON=ndcDt5 nmon -s 3" \; select-layout even-horizontal \; set-option status off'

- name: Switch keyboard layout to US
  ini_file:
    path: /etc/default/keyboard
    section: null
    no_extra_spaces: yes
    option: XKBLAYOUT
    value: us

- name: Add the modules module
  modprobe:
    name: "{{ item }}"
  loop: "{{ enable_kernel_modules }}"

- name: Load modules during boot
  copy:
    dest: /etc/modules-load.d/{{ item }}.conf
    content: |
      {{ item }}
  loop: "{{ enable_kernel_modules }}"

- name: Change params in /boot/config.txt
  blockinfile:
    path: /boot/config.txt
    block: "{{ boot_config_parameters }}"
  notify: reboot

- name: Enable watchdog
  ini_file:
    path: /etc/systemd/system.conf
    no_extra_spaces: yes
    section: "Manager"
    option: "RuntimeWatchdogSec"
    value: "10"
  notify: reload systemd

- name: Update all packages
  apt:
    name: "*"
    state: latest
    install_recommends: no
    update_cache: yes
  register: result
  until: result is succeeded

- name: Add an Apt signing keys
  apt_key:
    url: "{{ item }}"
  loop:
    - https://packages.grafana.com/gpg.key

- name: Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: grafana

- name: Install packages
  apt:
    name: "{{ rpi_packages }}"
    install_recommends: no
  register: result
  until: result is succeeded

- name: Install additional packages
  apt:
    name: "{{ rpi_packages_additional }}"
    install_recommends: no

- name: Stop services and disable them
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ rpi_disable_boot_services }}"

- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Run all hanlers
  meta: flush_handlers

- name: Create directory for mc inside /etc/skel
  file:
    path: /etc/skel/.config/mc/
    state: directory
    mode: 0700

- name: Create /etc/skel/.config/mc/ini file
  ini_file:
    path: /etc/skel/.config/mc/ini
    no_extra_spaces: yes
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - section: Midnight-Commander
      option: auto_save_setup
      value: 'false'
    - section: Midnight-Commander
      option: drop_menus
      value: 'true'
    - section: Midnight-Commander
      option: editor_return_does_auto_indent
      value: 'false'
    - section: Layout
      option: keybar_visible
      value: 'false'
    - section: Layout
      option: menubar_visible
      value: 'false'
    - section: Layout
      option: message_visible
      value: 'false'
    - section: Panels
      option: navigate_with_arrows
      value: 'true'

- name: Copy mc configuration to root direcotry
  copy:
    src: /etc/skel/.config
    dest: /root/
    remote_src: yes

- name: Copy mc configuration to pi home direcotry
  copy:
    src: /etc/skel/.config
    dest: /home/pi/
    owner: pi
    group: pi
    remote_src: yes

- name: Put "mc" alias into /etc/profile.d/my-mc.sh
  copy:
    dest: /etc/profile.d/my-mc.sh
    content: |
      [ -n "${BASH_VERSION}${KSH_VERSION}${ZSH_VERSION}" ] || return 0
      alias mc='. /usr/lib/mc/mc-wrapper.sh --nomouse'

- name: Tweak vim
  copy:
    dest: /etc/vim/vimrc.local
    content: |
      set laststatus=2
      set statusline=%F%m%r%h%w\ (%{&ff}){\%Y}[%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
      set ttymouse=

- name: Tweak logrotate (/etc/logrotate.conf)
  blockinfile:
    dest: /etc/logrotate.conf
    insertafter: "^create"
    block: |
      compress
      compresscmd /usr/bin/xz
      compressoptions -9
      uncompresscmd /usr/bin/unxz
      compressext .xz

- name: Configure dma auth.conf
  lineinfile:
    path: /etc/dma/auth.conf
    regexp: ".*|smtp.gmail.com:.*"
    line: "{{ smtp_gmail_auth_user }}|smtp.gmail.com:{{ smtp_gmail_auth_password }}"

- name: Configure dma dma.conf
  blockinfile:
    dest: /etc/dma/dma.conf
    block: |
      SMARTHOST smtp.gmail.com
      PORT 587
      AUTHPATH /etc/dma/auth.conf
      SECURETRANSFER
      STARTTLS
      INSECURE

- name: Configure email notification after reboot
  template:
    dest: /etc/rc.local
    src: files/etc/rc.local.j2

- name: Modify Unattended upgrade settings
  replace:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^//Unattended-Upgrade::Mail "root";', replace: 'Unattended-Upgrade::Mail "root";' }
    - { regexp: '^//Unattended-Upgrade::Remove-Unused-Dependencies "false";', replace: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }

- name: Install bcmstat.sh script
  get_url:
    dest: /usr/local/bin/
    url: https://raw.githubusercontent.com/MilhouseVH/bcmstat/master/bcmstat.sh
    mode: 0755

- name: Autoremove unused packages
  apt:
    autoremove: yes

###############################
# Prometheus Node Exporter
###############################

- name: Add user 'prometheus' to video group to be able to get GPU temperature
  user:
    name: prometheus
    append: yes
    groups: video

- name: Configure prometheus-node-exporter
  blockinfile:
    dest: /etc/default/prometheus-node-exporter
    block: |
      ARGS="\
        --collector.diskstats.ignored-devices=^(ram|loop|fd)\d+$ \
        --collector.filesystem.ignored-mount-points=^/(dev|proc|run|sys)($|/) \
        --collector.interrupts \
        --collector.meminfo_numa \
        --collector.mountstats \
        --collector.netstat.fields=(.*) \
        --collector.tcpstat \
        --collector.vmstat.fields=(.*) \
      "
  notify: restart prometheus-node-exporter

- name: Download RPi exporter
  unarchive:
    src: https://github.com/lukasmalkmus/rpi_exporter/releases/download/v{{ rpi_explorer_version }}/rpi_exporter-{{ rpi_explorer_version }}.linux-{{ ansible_architecture | regex_replace('l$', '')}}.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /usr/local/bin/rpi_exporter
  register: rpi_exporter_unarchive

- name: Move rpi_exporter binary to /usr/local/bin
  copy:
    src: /tmp/rpi_exporter-{{ rpi_explorer_version }}.linux-{{ ansible_architecture | regex_replace('l$', '')}}/rpi_exporter
    remote_src: yes
    mode: 0755
    dest: /usr/local/bin/rpi_exporter
  when: rpi_exporter_unarchive.changed

- name: Add RPi exporter target to Prometheus
  blockinfile:
    dest: /etc/prometheus/prometheus.yml
    block: |2
        - job_name: rpi
          static_configs:
          - targets: ['localhost:9243']
  notify: restart prometheus

- name: Add rpi_exporter to systemd
  get_url:
    url: https://raw.githubusercontent.com/lukasmalkmus/rpi_exporter/master/systemd/rpi_exporter.service
    dest: /etc/systemd/system/rpi_exporter.service
  notify:
    - reload systemd
    - restart rpi_exporter

###############################
# Grafana
###############################

- name: Grafana configuration
  ini_file:
    path: /etc/grafana/grafana.ini
    section: auth.anonymous
    option: enabled
    value: 'true'
  notify: restart grafana

- name: Update grafana user password
  uri:
    url: "http://localhost:3000/api/user/password"
    user: "admin"
    password: "admin"
    force_basic_auth: true
    method: PUT
    body_format: json
    body:
      oldPassword: admin
      newPassword: "{{ grafana_admin_password }}"
      confirmNew: "{{ grafana_admin_password }}"
  ignore_errors: yes

- name: Check if the grafana user is already present in Grafana
  uri:
    url: "http://localhost:3000/api/org/users"
    user: "admin"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  register: uri_grafana_user

- name: Create grafana user
  uri:
    url: "http://localhost:3000/api/admin/users"
    user: "admin"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
    method: POST
    body_format: json
    body:
      email: "{{ grafana_user }}@{{ inventory_hostname }}"
      login: "{{ grafana_user }}"
      password: "{{ grafana_user_password }}"
  when: uri_grafana_user.json[1] is not defined

- name: Create Prometheus datasource for Grafana (prometheus-node_exporter)
  grafana_datasource:
    name: "datasource-prometheus-node_exporter"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    ds_type: "prometheus"
    ds_url: "http://localhost:9090"
    is_default: yes

- name: Download grafana dashboards
  get_url:
    url: "{{ item.download_url }}"
    dest: /var/tmp/{{ item.download_url.split('/')[5] }}.json
  loop: "{{ rpi_grafana_dasboards }}"

- name: Replace variables inside dahboard json files
  replace:
    path: /var/tmp/{{ item.download_url.split('/')[5] }}.json
    regexp: '"datasource": "\$\{.*\}",'
    replace: '"datasource": "datasource-prometheus-node_exporter",'
  loop: "{{ rpi_grafana_dasboards }}"

- name: Check if the dashboard already exists
  uri:
    url: "http://localhost:3000/api/search"
    user: "admin"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: true
  register: grafana_dashboards_list

- name: Import Grafana dashboard
  grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    org_id: "1"
    message: Updated by ansible
    overwrite: yes
    path: /var/tmp/{{ item.download_url.split('/')[5] }}.json
  when: item.name not in grafana_dashboards_list | json_query('json[*].title')
  loop: "{{ rpi_grafana_dasboards }}"
