---
# GitHub Actions workflow for Semantic Pull Request validation
# Validates that pull request titles follow conventional commits format
# https://www.conventionalcommits.org/
name: semantic-pull-request

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.MY_RENOVATE_GITHUB_APP_ID }}
          private-key: ${{ secrets.MY_RENOVATE_GITHUB_PRIVATE_KEY }}

      - name: Validate semantic pull request title
        uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
